version: 0.2

phases:
  pre_build:
    commands:
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain tango --domain-owner 802306197541 --query authorizationToken --output text`
  build:
    commands:
      - echo Running the terraform plan...
      - ./run.sh
      - ./mvnw -B deploy
